# Lists

- containers that hold variables
- the variables can be a mix of things


In [4]:
# lists
list1 = [0, 1.0, "hello", 10, "world"]
list2 = [0, 0, 0, 0]
list1

[0, 1.0, 'hello', 10, 'world']

In [21]:
list1[0:5]

[0, 1.0, 'hello', 10, 'world']

accessing an element of list

Python indexes at 0, so first element of a list is list1[0]

accessing a portion of list (also called slicing)

In [14]:
list1[0:2]

[0, 1.0]

can do math with lists and treat them like variables

In [22]:
list1

[0, 1.0, 'hello', 10, 'world']

In [34]:
z = list1[1] + 3
z**2

16.0

can also append to a list

In [35]:
list1

[0, 1.0, 'hello', 10, 'world']

In [44]:
list1.append(0)

In [45]:
list1

[0, 1.0, 'hello', 10, 'world', 0, 0, 0, 0, 0, 0, 0, 0, 0]

# Arrays

- Slightly different from lists
- are imported from `numpy`
- can only have numbers in them
- can not "expand" i.e. `append` doesn't work
- can handle "math" operations better/faster
- are faster in general
- have inherit attributes (like size) (Table 4.1)

In [46]:
import numpy as np

In [49]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

There are various ways to make arrays
- np.linspace or logspace (start, stop, N)
- np.zeros
- np.arange (start, stop, step)
- np.ones

Pg 63 of book has more details

In [57]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Can do more math operations on the entire array

slicing is probably the most powerful thing but also the most confusing when you are first using it


In [59]:
arr

array([0., 1., 2., 3., 4., 5.])

In [58]:
arr = np.linspace(0, 5, 6)
arr[0:3]

array([0., 1., 2.])

In [61]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [65]:
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [64]:
arr = np.ones((6,6))
# arr[0:3,:] *= 2
arr[0:3,:] + 3

array([[4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4.]])

# Lesson Plan
- want to finish up the last of this chapter (slicing and boolean stuff)
- next week will look at for loops and if-else statements
- while this week and last week I slowed down for slicing because it's a tougher to grasp topic next week should be faster and will lead right into plotting which can let you have some fun with the data we have and maybe any data you want to look at (:

In [12]:
# boolean masks
import numpy as np

arr = np.ones(10)
arr += 2
arr

arr[3]  += 5

arr

# boolean mask
arr <= 3

# saving it as a variable
y = arr <= 3

# using it in your array

arr[y]

array([3., 3., 3., 3., 3., 3., 3., 3., 3.])

# Exercises
- 4.6.2
- 4.6.4:a-d
- 4.6.8